version: "1.0"
info:
  model: int-scaffold
packages:
- name: JcHelloWorldAPI
  version: "1.1"
  gitServerName: johnpcarter
  gitUrl: https://github.com/johnpcarter
  gitUsername: johnpcarter
  gitBranch: main
  gitTag: v1.0.0
- name: JcProjectWithVersioningProject
  gitServerName: johnpcarter
  gitUrl: https://github.com/johnpcarter
  gitUsername: johnpcarter
  gitBranch: main
services:
- serviceName: project.jcprojectwithversioning.integrations:SayHi
  packages:
  - name: JcProjectWithVersioningProject
    version: "1.0"
  - name: JcHelloWorldAPI
    version: "1.1"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.1.0.0.2090
- serviceName: jc.helloworld._priv.jdbc:logMessage
  packages:
  - name: JcHelloWorldAPI
    version: "1.1"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
